version: '2.1'

services:
    opensbis.db:
        image: opensbis/database
        build:
            context: ./src/Database/
            dockerfile: Dockerfile
        environment:
            - POSTGRES_USER=opensbis
            - POSTGRES_PASSWORD=FbaMCxGDtq69Frmk
            - IDSRV_USER=opensbis_idsrv
            - IDSRV_PASSWD=DgdYmTGUjs8rkv5B
        ports:
            - 5432:5432

    opensbis.web:
        image: opensbis/webserver
        build:
            context: ./src/OpenSBIS/
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionString=User ID=opensbis;Password=FbaMCxGDtq69Frmk;Host=opensbis.db;Port=5432;Database=opensbis;
            - IDSRV_URL=http://identityserver.web
            - IDSRV_API=api1
        ports:
            - 5000:80

    identityserver.web:
        image: opensbis/identityserver
        build:
            context: ./src/IdentityServer/
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionString=User ID=opensbis_idsrv;Password=DgdYmTGUjs8rkv5B;Host=opensbis.db;Port=5432;Database=opensbis_idsrv;
        ports:
            - 5001:80

    adminer:
        image: adminer
        ports:
            - 8080:8080