version: '2.1'

services:
    opensbis.db:
        image: opensbis/database
        build:
            context: ./src/Database/
            dockerfile: Dockerfile
        environment:
            - POSTGRES_USER=opensbis
            - POSTGRES_PASSWORD=FbaMCxGDtq69Frmk
            - IDSRV_USER=opensbis_idsrv
            - IDSRV_PASSWD=DgdYmTGUjs8rkv5B

    opensbis.ui:
        image: opensbis/webui
        build:
            context: ./src/OpenSBIS.UI/
            dockerfile: Dockerfile
            args:
                - API_URL=http://localhost:5001
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - IDSRV_URL=http://localhost:5002
            - IDSRV_API=api1
        ports:
            - 5000:80

    opensbis.api:
        image: opensbis/webapi
        build:
            context: ./src/OpenSBIS.API/
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionString=User ID=opensbis;Password=FbaMCxGDtq69Frmk;Host=opensbis.db;Port=5432;Database=opensbis;
            - IDSRV_URL=http://localhost:5002
            - IDSRV_API=api1
            - WEB_URL=http://localhost:5000
        ports:
            - 5001:80

    identityserver.web:
        image: opensbis/identityserver
        build:
            context: ./src/IdentityServer/
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionString=User ID=opensbis_idsrv;Password=DgdYmTGUjs8rkv5B;Host=opensbis.db;Port=5432;Database=opensbis_idsrv;
            - MVC_URL=http://localhost:5000
            - IDSRV_URL=http://localhost:5002
        ports:
            - 5002:80

    adminer:
        image: adminer
        ports:
            - 8080:8080

